# frps.toml
bindPort = 7000

# নিরাপত্তার জন্য একটি টোকেন সেট করতে পারেন (ঐচ্ছিক, তবে রেকমেন্ডেড)
auth.token = "nekotunnel_secret_123"

# কোন পোর্টগুলো আমরা ক্লায়েন্টকে ব্যবহার করতে দেব 
# আমরা রেলওয়ের জন্য 6000 পোর্টটি নির্দিষ্ট করে দিচ্ছি
allowPorts = [
  { single = "6000" }
]
